### ISSUE TITLE
Transliteration from tamiL - add option to use ś instead of s

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#116]
namaste!

```
பல்லாண்டு பல்லாண்டு பல்லாயிரத்தாண்டு
        பல கோடி நூறாயிரம்
மல்லாண்ட திண்தோள் மணிவண்ணா. உன்
        செவ்வடி செவ்வி திருக்காப்பு.
        
 ```       

This should be transliterated as 

![image](https://user-images.githubusercontent.com/2664797/118346461-3886b080-b559-11eb-88b9-500f7772d3e3.png)

as per strong living tradition ( http://prapatti.com/slokas/english/tiruvarangampaasurangal.pdf and https://www.youtube.com/watch?v=KRrU0ZB9MjM ) .

Whereas it is transliterated as:

```
pallāṇḍu pallāṇḍu pallāyirattāṇḍu
pala koḍi nūṟāyiram
mallāṇḍa tiṇdol̤ maṇivaṇṇā. un
sĕvvaḍi sĕvvi tirukkāppu.
```

https://www.projectmadurai.org/pm_etexts/utf8/pmuni0621_eng.html says:

> In Pronunciation. Nasals and medial sounds have only one pronunciation: ng, nj, ṇ, n and m. y, r, ṛ, v, l, ḷ and zh. The stops k, ch, ṭ, th, and p are unvoiced when they occur initially in a word. In the middle of a word in between vowels, they are pronounced as unvoiced stops. In the middle of the word if they are unvoiced stops, Tamil writing indicates these with double letters. The soft consonants h/g, s, ḍ, d, b are voiced and occur in the middle of a word between vowels. The Tamil writing system indicates these with single letter between vowels. The soft consonants may also occur after a nasal: ngg, nj, ṇḍ, nd, and mb.

Above, I don't see a rule to use ś instead of s (which makes me think that the dominant tamiL dialect doesn't agree) . But it would be a useful option to add for most target scripts.

[Motivation: I am rather eager to devour 4000 divya prabandhams, but script is an impediment.]

**Comment by nsesha92** [comment]
1. correct one is சேவடி செவ்வி and not செவ்வடி செவ்வி.
2. In TamiL differentiation should be made between ச & ஸ, even though written as ka/ca/cha = ச.
3. To that extent, the existing Transcribe Tamil option works ok ( ச = ca to ஸ = sa)
4. Not sure if multiple options can be included to Transcribe ச to ஸ = sa, ஶ = śa and ṣa = ஷ

**Comment by vvasuki** [comment]
Reg. point 3 above: ச is currently transcribed as sa and not ca in "transcribe tamil" mode - only when unchecked do I see a differentiation.

I don't understand why tamils don't use ஶ instead of ச here. Quite strange.

**Comment by GokulNC** [comment]
> I don't understand why tamils don't use ஶ instead of ச here. Quite strange.

To give some context:
Tamil Vaishnavas generally used the full Grantha script to ensure all Indic consonants are covered.
Today's Modern Tamil Script is very minimalistic (as in Tolkāppiyam) and allows only 4 additional non-Old-Tamil Grantha consonants (ஜ, ஷ, ஸ, ஹ).

Though Unicode includes ஶ, it is not generally used and approximated as ஷ/ஸ depending on context.
The only place where ஶ is generally used is ஸ்ரீ .
In extreme cases, even ஷ & ஸ are normalized as ச (irrespective of the word being Dravidian/Indic).

I think this issue is more because of Tamil Nadu politics' language-based anti-Aryan sub-nationalism rather than any logical reason. (Just like Hindustani being de-persianized and called as Hindi by the Indian govt)
Even Middle-Tamil's Pallava-Grantha script have coverage for all Indic consonants.

I have even seen some Tamil Vaishnavas entirely use the Malayalam script because of this reason for digital purposes.

The minimalistic Tamil script is actually enough if one removes all the Indic loanwords in Tamil. The transcribing of cha->sa, pa->ba, ka->ga, etc. would be handled by the Tolkāppiya grammar.
The issue occurs only when loanwords are introduced, for which the TN government stubbornly believes {ஜ, ஷ, ஸ, ஹ} would be enough.

---

Regarding your case, in Tamil Nadu temples, "செவ்வடி" is pronounced as "sĕvvaḍi", not "śĕvvaḍi".
The root "செவ்" comes from Tamil [சிவ](https://en.wiktionary.org/wiki/சிவ) meaning "reddish".

சிவப்பு (sivappu/chevappu), ಕೆಂಪು (kempu/chempu) are some cognates. (Telugu has diverged to ఎరుపు i guess)
So it's not possible to use "ś" in that place I believe.

**Comment by virtualvinodh** [comment]
`I don't understand why tamils don't use ஶ instead of ச here. Quite strange.
`

Reading /ச/ as /sha/  is not wide-spread. It is mostly a dialectal thing only used by some. 

IIUC: You want an option where word-initial /ச/ is transcribed to /ஶ/ as reflected in some traditional renderings of the Divyaprabandham. Is that right?

V

**Comment by vvasuki** [comment]
> IIUC: You want an option where word-initial /ச/ is transcribed to /ஶ/ as reflected in some traditional renderings of the Divyaprabandham. Is that right?

Yes.

> Tamil Vaishnavas generally used the full Grantha script to ensure all Indic consonants are covered.

Thanks for the info! How I wish the divyaprabandha-s were available digitized in such a complete script!! Alas - in its absence, all one can do is reconstruct the original. It's quite frustrating to make sense of tamil with dumb transliteration - https://twitter.com/zeneraalstuff/status/1404757536792727558 .

> Today's Modern Tamil Script is very minimalistic (as in Tolkāppiyam) and allows only 4 additional non-Old-Tamil Grantha consonants (ஜ, ஷ, ஸ, ஹ).
> 
> Though Unicode includes ஶ, it is not generally used and approximated as ஷ/ஸ depending on context.
> The only place where ஶ is generally used is ஸ்ரீ .
> In extreme cases, even ஷ & ஸ are normalized as ச (irrespective of the word being Dravidian/Indic).

That's what I feel so odd. Might have the same justification as in the case of the use of anusvAras in place of ञ ङ etc..

> 
> Regarding your case, in Tamil Nadu temples, "செவ்வடி" is pronounced as "sĕvvaḍi", not "śĕvvaḍi".

I don't know about that - see links in the first post.

> The root "செவ்" comes from [சிவ](https://en.wiktionary.org/wiki/%E0%AE%9A%E0%AE%BF%E0%AE%B5) meaning "reddish".
> 
> சிவப்பு (sivappu/chevappu), ಕೆಂಪು (kempu/chempu) are some cognates. (Telugu has diverged to ఎరుపు i guess)
> So it's not possible to use "ś" in that place I believe.

I get that chem/ kem is the old root - but to me it's clear that ś is closer to ch than s!

**Comment by virtualvinodh** [comment]
I have added a new option called Transcribe Tamil (Dialectal). I have also seen this in Tamil books written in the Telugu script (hence using a phonetic as opposed to a phonemic orthography). Personally, I find it odd.  But it is what it is. If some do pronounce it that way, there is no harm in adding another option.

It should be available when I push the next update in a week or two.

V
