### ISSUE TITLE
Post-option to use E/O for long-vowel and e/o for short

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha#249]
As of now for Dravidian langauges, ITRANS output uses `^o` for short and `o` for long, as the scheme was originally meant only for mainland Indo-Aryan languages which only has long vowels.

Tamil Example: `ஒளி. ஓசை.` --> `^oLi. ochai.`

Would be great if a post-option can be added, which can romanize it to `oLi. Ochai.` (or atleast `OLi. ochai`)

**Comment by GokulNC** [comment]
If it's not too much to ask, another option (both pre and post) to consider `c` as `च` and `ch` as `छ` instead of `ch` and `chh`, as compatible with ISO. This can be switched off by default.

**Comment by nsesha92** [comment]
^e/^o and e/o are for short and long e/o for Northern Brahmi-derived languages.
e/o, E/O are for short and long e/o for Southern Brahmi-derived languages.

ITRANS 5.3 coding, cannot be changed. You can check the itrans 5.3 spreadsheet. 

This is fixed/made uniform, without any North-South divide, and per ISO15919 standard, if you LOAD and use the iso-based input spreadsheet. 

As for c/ch, again, its ITRANS 5.3 coding, being used since 1990 and cannot be changed for backward compatibility.

Also in Tamil, c is sometimes used as k also (cauvery vs kAveri etc.)

**Comment by GokulNC** [comment]
Thank you @nsesha92 .

> _^e/^o and E/O are for short and long e/o for Southern Brahmi-derived languages._

Yes. But when I convert `ஒளி. ஓசை.` to ITRANS, it gives only the former variant: `^oLi. ochai.`
I was requesting that the the latter variant `OLi. ochai.` be available as well, optionally for interested users.

> _ITRANS 5.3 coding, cannot be changed._

Indeed yes, but this could be a custom option that can be supported by Aksharamukha.
Because it does not feel good to use uppercase for some long-vowels (`A`, `I`, `U`) and lowercase for others (`e`, `o`). Having consistency would be great, if the user really wants it.

> _Good feature is that Aksharamukha gives this 'swapping option' - E/O for long, e/o for short._
Correct. But this is only available when ITRANS is used as input, not when ITRANS is to be produced as output.

> _Also in Tamil, c is sometimes used as k also (cauvery vs kAveri etc.)_

This is because of English influence during the British Raj. _cauvery_ is the anglicized spelling of _kAveri_

**Comment by virtualvinodh** [comment]
Will be pushed in the next update.

**Comment by nsesha92** [comment]
not implemented in this release.

![image](https://github.com/virtualvinodh/aksharamukha/assets/33624096/085891ef-f98b-42ef-95c5-fbe9174789bc)
