### ISSUE TITLE
Fix Readable Roman: \nja -> \nya

### ISSUE THREAD

**Issue by virtualvinodh** [virtualvinodh/aksharamukha#91]

**Comment by geethub** [comment]
nja vyanjga ....type in readable 
 ञ,व्यञ्ग...........output
nya,vyanjga...output in readable

**Comment by nsesha92** [comment]
1. ஞ - have both nya (ஞாயிறு, ஞானம்) and nja (இஞ்சி) depending on the situation
2. gna is for skt ज्ञान = (ஜ்+ஞா) ன.

**Comment by virtualvinodh** [comment]
done

**Comment by virtualvinodh** [comment]
> 1. ஞ - have both nya (ஞாயிறு, ஞானம்) and nja (இஞ்சி) depending on the situation
> 2. gna is for skt ज्ञान = (ஜ்+ஞா) ன.

I particularly don't like gna for ज्ञ, jnya sounds closer to the original pronunciation.

V

**Comment by nsesha92** [comment]
all these are used: gnan, gyan, jnan (worst) and jnyan

jnanabharathi / Gnana Bharathi Bengaluru
Jnana Sanjeevini Medical Centre Bengaluru
Sadguru Gnanananda Hall Chennai
jnana bhumi 
jnanpith award

No doubt, by ISO code name, its j+nya

However, when pronounced it is more like g+ya = ग्‌ + य

j+n = g

I feel gyan is closest and gnan the 2nd best. and this reduces one less letter to type.

its like laxmi instead of lakshmi ( kSh = x ).

Azhagi uses xa for sha and Xa for kSha
